### ISSUE TITLE
Does not work on PyPy.

### ISSUE THREAD

**Issue by Marusoftware** [jwansek/tkFileBrowser#1]
Can't use tkfilebrowser on PyPy 3.7 on linux.
It gives me the error when using "askopenfilename" function(for example).
```
Traceback (most recent call last):
  File "./test.py", line 33, in <module>
    url=askopenfilename()
  File "/path/to/tkfilebrowser/functions.py", line 143, in askopenfilename
    title=title, **kwargs)
  File "/path/to/tkfilebrowser/filebrowser.py", line 314, in __init__
    wrapper = TooltipTreeWrapper(self.left_tree)
  File "/path/to/tkfilebrowser/tooltip.py", line 86, in __init__
    self.tooltip = Tooltip(tree, **kwargs)
  File "/path/to/tkfilebrowser/tooltip.py", line 45, in __init__
    self.attributes('-type', 'tooltip')
  File "/usr/share/pypy/pypy3.7/lib-python/3/tkinter/__init__.py", line 1788, in wm_attributes
    return self.tk.call(args)
  File "/usr/share/pypy/pypy3.7/lib_pypy/_tkinter/app.py", line 329, in call
    self.raiseTclError()
  File "/usr/share/pypy/pypy3.7/lib_pypy/_tkinter/app.py", line 178, in raiseTclError
    tklib.Tcl_GetStringResult(self.interp)).decode('utf-8'))
_tkinter.TclError: bad attribute "-type": must be -alpha, -topmost, -zoomed, or -fullscreen
```
The Tk Version is 8.5.7.
So, It seems "-type" attribute is not provided.(Look [here](https://wiki.tcl-lang.org/page/wm+attributes))

Thank you.

**Comment by Marusoftware** [comment]
Sorry.............
I put this wrong place...
